---
- name: Install and configure Nginx on multiple nodes
  hosts: all
  become: true
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
